add ci pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,7 @@
 name: CI
 
 on:
-  workflow_dispatch:
+  workflow_dispatch: {}
   push:
     branches:
       - master
@@ -21,68 +21,116 @@ on:
       - feature/**
 
 jobs:
+  # ======================================================
+  # BUILD STAGE
+  # ======================================================
   build:
     name: Build
     runs-on: ubuntu-24.04
 
     steps:
       - uses: actions/checkout@v4
+      - uses: extractions/setup-just@v2
 
-      - uses: actions/setup-java@v4
+      - name: Setup Java (Build JVM)
+        id: setup-build-jre
+        uses: actions/setup-java@v4
         with:
           distribution: temurin
-          java-version: 17
+          java-version: "17"
 
-      - uses: gradle/gradle-build-action@v3
-        with:
-          gradle-home-cache-cleanup: true
-
-      - name: Spotless format check
-        run: ./gradlew spotlessCheck
-
-      - name: Build artifacts and docs
-        run: ./gradlew assemble javadoc
-
-  test:
-    name: Test
-    runs-on: ubuntu-24.04
-
-    strategy:
-      fail-fast: false
-      matrix:
-        java-version: ["8", "11", "17", "21", "25"]
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - uses: actions/setup-java@v4
-        with:
-          distribution: temurin
-          java-version: ${{ matrix.java-version }}
-
-      - uses:  gradle/gradle-build-action@v3
+      - name: Set JAVA_HOME for Gradle
+        run: |
+          echo "JAVA_HOME=${{ steps.setup-build-jre.outputs.path }}" >> $GITHUB_ENV
+          echo "PATH=${{ steps.setup-build-jre.outputs.path }}/bin:$PATH" >> $GITHUB_ENV
 
       - name: Display Java version
         run: java -version
 
-      - name: Run tests
-        run: ./gradlew ci
+      - name: Spotless check
+        run: ./gradlew spotlessCheck --no-daemon
 
+      - name: Build artifacts and Javadoc
+        run: ./gradlew assemble javadoc --no-daemon
+
+  # ======================================================
+  # TEST STAGE
+  # ======================================================
+  test:
+    name: Test
+    runs-on: ubuntu-24.04
+    needs: build
+
+    strategy:
+      fail-fast: false
+      matrix:
+        java-version:
+          - "8"
+          - "11"
+          - "17"
+          - "21"
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: extractions/setup-just@v2
+
+      # Use Java 17 for Gradle (plugin classpath)
+      - name: Setup Build JVM (Gradle)
+        id: setup-build-jre
+        uses: actions/setup-java@v4
+        with:
+          distribution: temurin
+          java-version: "17"
+
+      # Use matrix JVM for running tests
+      - name: Setup Test JVM
+        id: setup-test-jre
+        uses: actions/setup-java@v4
+        with:
+          distribution: temurin
+          java-version: ${{ matrix.java-version }}
+
+      - name: Export Java Environments
+        run: |
+          echo "JAVA_HOME=${{ steps.setup-build-jre.outputs.path }}" >> $GITHUB_ENV
+          echo "JAVA_TEST_HOME=${{ steps.setup-test-jre.outputs.path }}" >> $GITHUB_ENV
+          echo "PATH=${{ steps.setup-build-jre.outputs.path }}/bin:$PATH" >> $GITHUB_ENV
+
+      - name: Display versions
+        run: |
+          ./gradlew --version
+          echo "Test JVM: $JAVA_TEST_HOME"
+          $JAVA_TEST_HOME/bin/java -version
+
+      - name: Run tests
+        run: ./gradlew test jacocoTestReport --no-daemon
+
+      - name: Upload test reports
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-reports-${{ matrix.java-version }}
+          path: build/reports/tests/test
+
+  # ======================================================
+  # PUBLISH STAGE
+  # ======================================================
   publish:
-    name: Publish to Maven Central
-    if: startsWith(github.ref, 'refs/tags/v')
+    name: Publish to Sonatype
+    if: >-
+      ((github.event_name == 'workflow_dispatch') || (github.event_name == 'push')) &&
+      startsWith(github.ref, 'refs/tags/v')
     needs: [build, test]
     runs-on: ubuntu-24.04
 
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/setup-java@v4
+      - name: Setup Java
+        id: setup-jre
+        uses: actions/setup-java@v4
         with:
           distribution: temurin
-          java-version: 17
-
-      - uses: gradle/gradle-build-action@v3
+          java-version: "17"
 
       - name: Import GPG key
         run: |
@@ -104,9 +152,15 @@ jobs:
           GPG_SIGNING_KEYID: ${{ secrets.GPG_SIGNING_KEYID }}
           GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
 
+  # ======================================================
+  # DOCS STAGE
+  # ======================================================
   publish-docs:
-    name: Publish Javadoc
-    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'beta')
+    name: Publish Javadocs
+    if: >-
+      ((github.event_name == 'workflow_dispatch') || (github.event_name == 'push')) &&
+      startsWith(github.ref, 'refs/tags/v') &&
+      !contains(github.ref, 'beta')
     needs: [build, test]
     runs-on: ubuntu-24.04
     permissions:
@@ -114,38 +168,42 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-
       - uses: actions/setup-java@v4
         with:
           distribution: temurin
-          java-version: 17
+          java-version: "17"
 
-      - uses: gradle/gradle-build-action@v3
-
-      - name: Publish Javadoc
+      - name: Publish Javadocs
         run: ./gradlew gitPublishPush --stacktrace --info
         env:
           GRGIT_USER: ${{ github.actor }}
           GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
 
+  # ======================================================
+  # COMPAT STAGE
+  # ======================================================
   compat:
-    name: Binary Compatibility Check
+    name: API Compatibility Check
     runs-on: ubuntu-24.04
+    needs: build
 
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/setup-java@v4
+      - name: Setup Java
+        uses: actions/setup-java@v4
         with:
           distribution: temurin
-          java-version: 17
+          java-version: "17"
 
-      - name: Install japi-compliance-checker
+      - name: Clone japi-compliance-checker
         run: git clone https://github.com/lvc/japi-compliance-checker ../japi-compliance-checker
 
-      - name: Build new JAR
-        run: ./gradlew jar
-      - run: mv build/libs/*.jar ../japi-compliance-checker/new.jar
+      - name: Build HEAD JAR
+        run: ./gradlew jar --no-daemon
+
+      - name: Copy new JAR
+        run: mv build/libs/*.jar ../japi-compliance-checker/new.jar
 
       - name: Checkout base branch
         uses: actions/checkout@v4
@@ -153,24 +211,27 @@ jobs:
           ref: ${{ github.event.pull_request.base.sha }}
 
       - name: Build base JAR
-        run: ./gradlew jar
-      - run: mv build/libs/*.jar ../japi-compliance-checker/old.jar
+        run: ./gradlew jar --no-daemon
+
+      - name: Copy old JAR
+        run: mv build/libs/*.jar ../japi-compliance-checker/old.jar
 
       - name: Run JAPI Compliance Checker
         run: |
           pushd ../japi-compliance-checker
-          perl japi-compliance-checker.pl -old old.jar -new new.jar --lib=${{ github.event.repository.name }} || echo "failed" > compliance_failure
+          perl japi-compliance-checker.pl -old old.jar -new new.jar --lib=mpesa-java-sdk || echo "failed" > compliance_failure
           popd
-          mv ../japi-compliance-checker/compat_reports/*/compat_report.html report.html
+          mv ../japi-compliance-checker/compat_reports/mpesa-java-sdk/*/compat_report.html report.html
 
-      - uses: actions/upload-artifact@v4
+      - name: Upload report
+        uses: actions/upload-artifact@v4
         with:
           name: JAPI Compliance Report
           path: report.html
 
-      - name: Fail if incompatible
+      - name: Fail on compatibility issues
         run: |
           if [ -f "../japi-compliance-checker/compliance_failure" ]; then
-            echo "Compatibility problems detected. Check the report artifact."
+            echo "⚠️ Compatibility problems detected! See artifact for details."
             exit 1
           fi
